"""add phone and address columns to patient model

Revision ID: 5abfcceb39cf
Revises: 8411a6a1edbe
Create Date: 2024-07-16 17:23:09.357525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abfcceb39cf'
down_revision = '8411a6a1edbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=False, server_default='123-456-7890'))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=False, server_default='1234 Apple St. Benson, MO 65377'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
