"""add notes column to appointment

Revision ID: e5a3326cab6c
Revises: 0729f98eba42
Create Date: 2024-07-11 13:40:57.357157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a3326cab6c'
down_revision = '0729f98eba42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_appointments')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('notes')

    op.create_table('_alembic_tmp_appointments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(), nullable=False),
    sa.Column('hour', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=True),
    sa.Column('doctor_id', sa.INTEGER(), nullable=True),
    sa.Column('reason', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name='fk_appointments_doctor_id_doctors'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='fk_appointments_patient_id_patients'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
